---
name: Deploy HTML Files to AppService - CMST385
on:
  push: null
  watch:
    - main
jobs:
  build-and-deploy:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@main
      - name: Deploy to Azure Web App
      - uses: azure/webapps-deploy@v1
      
env:
  name: cmst385-ahopkins27
  slot-name: production
  publish-profile: ${{secrets.AppServiceCMST385}}
